[phases.setup]
nixPkgs = [
  "bzip2",
  "gcc",
  "glibc",
  "zlib",
  "openssl",
  "yarn",
  "nodejs_20",
  "vips",
  "vips-dev"
]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"

[pack]
packageManager = "yarn"

[variables]
NODE_VERSION = "20"
NEXT_TELEMETRY_DISABLED = "1"
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"

[build]
cache = [
  "node_modules/.cache",
  ".next/cache"
] 