import { AddClaimAssignee } from "../definitions/AddClaimAssignee";
import { AddClaimAssigneeGroup } from "../definitions/AddClaimAssigneeGroup";
import { AddClaimAssigneeGroupResponse } from "../definitions/AddClaimAssigneeGroupResponse";
import { AddClaimAssigneeRepairOptions } from "../definitions/AddClaimAssigneeRepairOptions";
import { AddClaimAssigneeRepairOptionsResponse } from "../definitions/AddClaimAssigneeRepairOptionsResponse";
import { AddClaimAssigneeResponse } from "../definitions/AddClaimAssigneeResponse";
import { AddClaimAssigneeUserGroup } from "../definitions/AddClaimAssigneeUserGroup";
import { AddClaimAssigneeUserGroupResponse } from "../definitions/AddClaimAssigneeUserGroupResponse";
import { AddClaimExternalDocument } from "../definitions/AddClaimExternalDocument";
import { AddClaimExternalDocumentResponse } from "../definitions/AddClaimExternalDocumentResponse";
import { AddClaimInternalAssignee } from "../definitions/AddClaimInternalAssignee";
import { AddClaimInternalAssigneeResponse } from "../definitions/AddClaimInternalAssigneeResponse";
import { AddClaimJournalEntry } from "../definitions/AddClaimJournalEntry";
import { AddClaimJournalEntryResponse } from "../definitions/AddClaimJournalEntryResponse";
import { AddClaimPhotos } from "../definitions/AddClaimPhotos";
import { AddClaimPhotosResponse } from "../definitions/AddClaimPhotosResponse";
import { AddClaimQuestionnaire } from "../definitions/AddClaimQuestionnaire";
import { AddClaimQuestionnaireResponse } from "../definitions/AddClaimQuestionnaireResponse";
import { AddClaimUser } from "../definitions/AddClaimUser";
import { AddClaimUserResponse } from "../definitions/AddClaimUserResponse";
import { CompleteClaimQuestionnaire } from "../definitions/CompleteClaimQuestionnaire";
import { CompleteClaimQuestionnaireResponse } from "../definitions/CompleteClaimQuestionnaireResponse";
import { CreateCalendarEvent } from "../definitions/CreateCalendarEvent";
import { CreateCalendarEventResponse } from "../definitions/CreateCalendarEventResponse";
import { CreateClaim } from "../definitions/CreateClaim";
import { CreateClaimEstimate } from "../definitions/CreateClaimEstimate";
import { CreateClaimEstimateResponse } from "../definitions/CreateClaimEstimateResponse";
import { CreateClaimResponse } from "../definitions/CreateClaimResponse";
import { CreateClaimTask } from "../definitions/CreateClaimTask";
import { CreateClaimTaskFromTemplate } from "../definitions/CreateClaimTaskFromTemplate";
import { CreateClaimTaskFromTemplateResponse } from "../definitions/CreateClaimTaskFromTemplateResponse";
import { CreateClaimTaskResponse } from "../definitions/CreateClaimTaskResponse";
import { CreateUser } from "../definitions/CreateUser";
import { CreateUserResponse } from "../definitions/CreateUserResponse";
import { DeleteCalendarEvent } from "../definitions/DeleteCalendarEvent";
import { DeleteCalendarEventResponse } from "../definitions/DeleteCalendarEventResponse";
import { DeleteClaimTask } from "../definitions/DeleteClaimTask";
import { DeleteClaimTaskResponse } from "../definitions/DeleteClaimTaskResponse";
import { GetCalendarEvent } from "../definitions/GetCalendarEvent";
import { GetCalendarEventResponse } from "../definitions/GetCalendarEventResponse";
import { GetCalendarEvents } from "../definitions/GetCalendarEvents";
import { GetCalendarEventsResponse } from "../definitions/GetCalendarEventsResponse";
import { GetClaim } from "../definitions/GetClaim";
import { GetClaimAssignment } from "../definitions/GetClaimAssignment";
import { GetClaimAssignmentResponse } from "../definitions/GetClaimAssignmentResponse";
import { GetClaimAssignmentStatus } from "../definitions/GetClaimAssignmentStatus";
import { GetClaimAssignmentStatusResponse } from "../definitions/GetClaimAssignmentStatusResponse";
import { GetClaimContact } from "../definitions/GetClaimContact";
import { GetClaimContactResponse } from "../definitions/GetClaimContactResponse";
import { GetClaimCurrentOwner } from "../definitions/GetClaimCurrentOwner";
import { GetClaimCurrentOwnerResponse } from "../definitions/GetClaimCurrentOwnerResponse";
import { GetClaimDiagram } from "../definitions/GetClaimDiagram";
import { GetClaimDiagramResponse } from "../definitions/GetClaimDiagramResponse";
import { GetClaimDocumentV2Response1 } from "../definitions/GetClaimDocumentV2Response1";
import { GetClaimDocumentV21 } from "../definitions/GetClaimDocumentV21";
import { GetClaimEstimate } from "../definitions/GetClaimEstimate";
import { GetClaimEstimateResponse } from "../definitions/GetClaimEstimateResponse";
import { GetClaimExternalDocument } from "../definitions/GetClaimExternalDocument";
import { GetClaimExternalDocumentResponse } from "../definitions/GetClaimExternalDocumentResponse";
import { GetClaimForm } from "../definitions/GetClaimForm";
import { GetClaimFormResponse } from "../definitions/GetClaimFormResponse";
import { GetClaimPhoto } from "../definitions/GetClaimPhoto";
import { GetClaimPhotoResponse } from "../definitions/GetClaimPhotoResponse";
import { GetClaimQuestionnaire } from "../definitions/GetClaimQuestionnaire";
import { GetClaimQuestionnaireResponse } from "../definitions/GetClaimQuestionnaireResponse";
import { GetClaimResponse } from "../definitions/GetClaimResponse";
import { GetClaimStatus } from "../definitions/GetClaimStatus";
import { GetClaimStatusResponse } from "../definitions/GetClaimStatusResponse";
import { GetClaimTask } from "../definitions/GetClaimTask";
import { GetClaimTaskList } from "../definitions/GetClaimTaskList";
import { GetClaimTaskListResponse } from "../definitions/GetClaimTaskListResponse";
import { GetClaimTaskResponse } from "../definitions/GetClaimTaskResponse";
import { GetClaimVoiceAnnotation } from "../definitions/GetClaimVoiceAnnotation";
import { GetClaimVoiceAnnotationResponse } from "../definitions/GetClaimVoiceAnnotationResponse";
import { GetHandwrittenNote } from "../definitions/GetHandwrittenNote";
import { GetHandwrittenNoteResponse } from "../definitions/GetHandwrittenNoteResponse";
import { GetUsers } from "../definitions/GetUsers";
import { GetUsersResponse } from "../definitions/GetUsersResponse";
import { ImportClaimDiagram } from "../definitions/ImportClaimDiagram";
import { ImportClaimDiagramResponse } from "../definitions/ImportClaimDiagramResponse";
import { RemoveClaimAssignee } from "../definitions/RemoveClaimAssignee";
import { RemoveClaimAssigneeResponse } from "../definitions/RemoveClaimAssigneeResponse";
import { RemoveClaimInternalAssignee } from "../definitions/RemoveClaimInternalAssignee";
import { RemoveClaimInternalAssigneeResponse } from "../definitions/RemoveClaimInternalAssigneeResponse";
import { RemoveClaimUser } from "../definitions/RemoveClaimUser";
import { RemoveClaimUserResponse } from "../definitions/RemoveClaimUserResponse";
import { ResetUserPassword } from "../definitions/ResetUserPassword";
import { ResetUserPasswordResponse } from "../definitions/ResetUserPasswordResponse";
import { SetCalendarEvent } from "../definitions/SetCalendarEvent";
import { SetCalendarEventResponse } from "../definitions/SetCalendarEventResponse";
import { SetClaimAssignmentCustomFields } from "../definitions/SetClaimAssignmentCustomFields";
import { SetClaimAssignmentCustomFieldsResponse } from "../definitions/SetClaimAssignmentCustomFieldsResponse";
import { SetClaimAssignmentStatus } from "../definitions/SetClaimAssignmentStatus";
import { SetClaimAssignmentStatusInspectionScheduled } from "../definitions/SetClaimAssignmentStatusInspectionScheduled";
import { SetClaimAssignmentStatusInspectionScheduledResponse } from "../definitions/SetClaimAssignmentStatusInspectionScheduledResponse";
import { SetClaimAssignmentStatusJobScheduled } from "../definitions/SetClaimAssignmentStatusJobScheduled";
import { SetClaimAssignmentStatusJobScheduledResponse } from "../definitions/SetClaimAssignmentStatusJobScheduledResponse";
import { SetClaimAssignmentStatusResponse } from "../definitions/SetClaimAssignmentStatusResponse";
import { SetClaimContact } from "../definitions/SetClaimContact";
import { SetClaimContactResponse } from "../definitions/SetClaimContactResponse";
import { SetClaimCustomFields } from "../definitions/SetClaimCustomFields";
import { SetClaimCustomFieldsResponse } from "../definitions/SetClaimCustomFieldsResponse";
import { SetClaimPaymentStatus } from "../definitions/SetClaimPaymentStatus";
import { SetClaimPaymentStatusResponse } from "../definitions/SetClaimPaymentStatusResponse";
import { SetClaimStatus } from "../definitions/SetClaimStatus";
import { SetClaimStatusResponse } from "../definitions/SetClaimStatusResponse";
import { SetEstimateFinalization } from "../definitions/SetEstimateFinalization";
import { SetEstimateFinalizationResponse } from "../definitions/SetEstimateFinalizationResponse";
import { SetEstimateStatus } from "../definitions/SetEstimateStatus";
import { SetEstimateStatusResponse } from "../definitions/SetEstimateStatusResponse";
import { UnblockUser } from "../definitions/UnblockUser";
import { UnblockUserResponse } from "../definitions/UnblockUserResponse";
import { UpdateApiNotificationWebServiceKeys } from "../definitions/UpdateApiNotificationWebServiceKeys";
import { UpdateApiNotificationWebServiceKeysResponse } from "../definitions/UpdateApiNotificationWebServiceKeysResponse";
import { UpdateApiPassword } from "../definitions/UpdateApiPassword";
import { UpdateApiPasswordResponse } from "../definitions/UpdateApiPasswordResponse";
import { UpdateClaim } from "../definitions/UpdateClaim";
import { UpdateClaimCoverages } from "../definitions/UpdateClaimCoverages";
import { UpdateClaimCoveragesResponse } from "../definitions/UpdateClaimCoveragesResponse";
import { UpdateClaimEstimate } from "../definitions/UpdateClaimEstimate";
import { UpdateClaimEstimateResponse } from "../definitions/UpdateClaimEstimateResponse";
import { UpdateClaimEstimateScore } from "../definitions/UpdateClaimEstimateScore";
import { UpdateClaimEstimateScoreResponse } from "../definitions/UpdateClaimEstimateScoreResponse";
import { UpdateClaimResponse } from "../definitions/UpdateClaimResponse";
import { UpdateClaimTask } from "../definitions/UpdateClaimTask";
import { UpdateClaimTaskResponse } from "../definitions/UpdateClaimTaskResponse";
import { UpdateCompanies } from "../definitions/UpdateCompanies";
import { UpdateCompaniesResponse } from "../definitions/UpdateCompaniesResponse";
import { UpdateUser } from "../definitions/UpdateUser";
import { UpdateUserResponse } from "../definitions/UpdateUserResponse";
import { UpdateUsers } from "../definitions/UpdateUsers";
import { UpdateUsersResponse } from "../definitions/UpdateUsersResponse";

export interface SymbilityClaimsServiceSoap12 {
    AddClaimAssignee(addClaimAssignee: AddClaimAssignee, callback: (err: any, result: AddClaimAssigneeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimAssigneeGroup(addClaimAssigneeGroup: AddClaimAssigneeGroup, callback: (err: any, result: AddClaimAssigneeGroupResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimAssigneeUserGroup(addClaimAssigneeUserGroup: AddClaimAssigneeUserGroup, callback: (err: any, result: AddClaimAssigneeUserGroupResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimInternalAssignee(addClaimInternalAssignee: AddClaimInternalAssignee, callback: (err: any, result: AddClaimInternalAssigneeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimJournalEntry(addClaimJournalEntry: AddClaimJournalEntry, callback: (err: any, result: AddClaimJournalEntryResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimPhotos(addClaimPhotos: AddClaimPhotos, callback: (err: any, result: AddClaimPhotosResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimUser(addClaimUser: AddClaimUser, callback: (err: any, result: AddClaimUserResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimExternalDocument(addClaimExternalDocument: AddClaimExternalDocument, callback: (err: any, result: AddClaimExternalDocumentResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateCalendarEvent(createCalendarEvent: CreateCalendarEvent, callback: (err: any, result: CreateCalendarEventResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateClaim(createClaim: CreateClaim, callback: (err: any, result: CreateClaimResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateClaimEstimate(createClaimEstimate: CreateClaimEstimate, callback: (err: any, result: CreateClaimEstimateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateClaimEstimate(updateClaimEstimate: UpdateClaimEstimate, callback: (err: any, result: UpdateClaimEstimateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DeleteCalendarEvent(deleteCalendarEvent: DeleteCalendarEvent, callback: (err: any, result: DeleteCalendarEventResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCalendarEvent(getCalendarEvent: GetCalendarEvent, callback: (err: any, result: GetCalendarEventResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCalendarEvents(getCalendarEvents: GetCalendarEvents, callback: (err: any, result: GetCalendarEventsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaim(getClaim: GetClaim, callback: (err: any, result: GetClaimResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimAssignment(getClaimAssignment: GetClaimAssignment, callback: (err: any, result: GetClaimAssignmentResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimContact(getClaimContact: GetClaimContact, callback: (err: any, result: GetClaimContactResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimCurrentOwner(getClaimCurrentOwner: GetClaimCurrentOwner, callback: (err: any, result: GetClaimCurrentOwnerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimDiagram(getClaimDiagram: GetClaimDiagram, callback: (err: any, result: GetClaimDiagramResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ImportClaimDiagram(importClaimDiagram: ImportClaimDiagram, callback: (err: any, result: ImportClaimDiagramResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimDocument_v2(getClaimDocumentV2: GetClaimDocumentV21, callback: (err: any, result: GetClaimDocumentV2Response1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimEstimate(getClaimEstimate: GetClaimEstimate, callback: (err: any, result: GetClaimEstimateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimForm(getClaimForm: GetClaimForm, callback: (err: any, result: GetClaimFormResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimPhoto(getClaimPhoto: GetClaimPhoto, callback: (err: any, result: GetClaimPhotoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimVoiceAnnotation(getClaimVoiceAnnotation: GetClaimVoiceAnnotation, callback: (err: any, result: GetClaimVoiceAnnotationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimExternalDocument(getClaimExternalDocument: GetClaimExternalDocument, callback: (err: any, result: GetClaimExternalDocumentResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHandwrittenNote(getHandwrittenNote: GetHandwrittenNote, callback: (err: any, result: GetHandwrittenNoteResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimStatus(getClaimStatus: GetClaimStatus, callback: (err: any, result: GetClaimStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimAssignmentStatus(getClaimAssignmentStatus: GetClaimAssignmentStatus, callback: (err: any, result: GetClaimAssignmentStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RemoveClaimInternalAssignee(removeClaimInternalAssignee: RemoveClaimInternalAssignee, callback: (err: any, result: RemoveClaimInternalAssigneeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RemoveClaimAssignee(removeClaimAssignee: RemoveClaimAssignee, callback: (err: any, result: RemoveClaimAssigneeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RemoveClaimUser(removeClaimUser: RemoveClaimUser, callback: (err: any, result: RemoveClaimUserResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetCalendarEvent(setCalendarEvent: SetCalendarEvent, callback: (err: any, result: SetCalendarEventResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetClaimContact(setClaimContact: SetClaimContact, callback: (err: any, result: SetClaimContactResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetClaimCustomFields(setClaimCustomFields: SetClaimCustomFields, callback: (err: any, result: SetClaimCustomFieldsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetClaimAssignmentCustomFields(setClaimAssignmentCustomFields: SetClaimAssignmentCustomFields, callback: (err: any, result: SetClaimAssignmentCustomFieldsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetClaimPaymentStatus(setClaimPaymentStatus: SetClaimPaymentStatus, callback: (err: any, result: SetClaimPaymentStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetClaimStatus(setClaimStatus: SetClaimStatus, callback: (err: any, result: SetClaimStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEstimateStatus(setEstimateStatus: SetEstimateStatus, callback: (err: any, result: SetEstimateStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEstimateFinalization(setEstimateFinalization: SetEstimateFinalization, callback: (err: any, result: SetEstimateFinalizationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetClaimAssignmentStatus(setClaimAssignmentStatus: SetClaimAssignmentStatus, callback: (err: any, result: SetClaimAssignmentStatusResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetClaimAssignmentStatusInspectionScheduled(setClaimAssignmentStatusInspectionScheduled: SetClaimAssignmentStatusInspectionScheduled, callback: (err: any, result: SetClaimAssignmentStatusInspectionScheduledResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetClaimAssignmentStatusJobScheduled(setClaimAssignmentStatusJobScheduled: SetClaimAssignmentStatusJobScheduled, callback: (err: any, result: SetClaimAssignmentStatusJobScheduledResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateCompanies(updateCompanies: UpdateCompanies, callback: (err: any, result: UpdateCompaniesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateUsers(updateUsers: UpdateUsers, callback: (err: any, result: UpdateUsersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateUser(createUser: CreateUser, callback: (err: any, result: CreateUserResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateUser(updateUser: UpdateUser, callback: (err: any, result: UpdateUserResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ResetUserPassword(resetUserPassword: ResetUserPassword, callback: (err: any, result: ResetUserPasswordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UnblockUser(unblockUser: UnblockUser, callback: (err: any, result: UnblockUserResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetUsers(getUsers: GetUsers, callback: (err: any, result: GetUsersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateClaim(updateClaim: UpdateClaim, callback: (err: any, result: UpdateClaimResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateClaimCoverages(updateClaimCoverages: UpdateClaimCoverages, callback: (err: any, result: UpdateClaimCoveragesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateClaimTask(createClaimTask: CreateClaimTask, callback: (err: any, result: CreateClaimTaskResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateClaimTaskFromTemplate(createClaimTaskFromTemplate: CreateClaimTaskFromTemplate, callback: (err: any, result: CreateClaimTaskFromTemplateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateClaimTask(updateClaimTask: UpdateClaimTask, callback: (err: any, result: UpdateClaimTaskResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DeleteClaimTask(deleteClaimTask: DeleteClaimTask, callback: (err: any, result: DeleteClaimTaskResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimTask(getClaimTask: GetClaimTask, callback: (err: any, result: GetClaimTaskResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimTaskList(getClaimTaskList: GetClaimTaskList, callback: (err: any, result: GetClaimTaskListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimAssigneeRepairOptions(addClaimAssigneeRepairOptions: AddClaimAssigneeRepairOptions, callback: (err: any, result: AddClaimAssigneeRepairOptionsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddClaimQuestionnaire(addClaimQuestionnaire: AddClaimQuestionnaire, callback: (err: any, result: AddClaimQuestionnaireResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetClaimQuestionnaire(getClaimQuestionnaire: GetClaimQuestionnaire, callback: (err: any, result: GetClaimQuestionnaireResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateApiPassword(updateApiPassword: UpdateApiPassword, callback: (err: any, result: UpdateApiPasswordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateApiNotificationWebServiceKeys(updateApiNotificationWebServiceKeys: UpdateApiNotificationWebServiceKeys, callback: (err: any, result: UpdateApiNotificationWebServiceKeysResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateClaimEstimateScore(updateClaimEstimateScore: UpdateClaimEstimateScore, callback: (err: any, result: UpdateClaimEstimateScoreResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CompleteClaimQuestionnaire(completeClaimQuestionnaire: CompleteClaimQuestionnaire, callback: (err: any, result: CompleteClaimQuestionnaireResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
