const dimensionMap = {
  APPDRY: 'EA',
  APPDW: 'EA',
  APPMWS: 'EA',
  APPRF: 'EA',
  APPRG: 'EA',
  APPWAS: 'EA',
  CABCT: 'LF',
  CABLOW: 'LF',
  CABUP: 'LF',
  CABVAN: 'EA',
  DORAV: 'EA',
  DORBI: 'EA',
  DORX: 'EA',
  ELEOSCOV: 'EA',
  FCCAV: 'SF',
  FCTAV: 'SF',
  FNCB: 'LF',
  HVCREG: 'EA',
  LITAV: 'EA',
  LITBAR: 'EA',
  LITFNL: 'EA',
  LITHG: 'EA',
  LITR: 'EA',
  PLMPSNK: 'EA',
  PLMSNK: 'EA',
  PLMTLT: 'EA',
  PLMWH: 'EA',
  TILCTTLB: 'LF',
}

export default dimensionMap
